import time
print("welcome to the Quiz,where you can know your self")
print("---"*50)
name = input("enter your name: ")
age = int(input("How old you are :"))
location = input("which city do you live in: ")
fav_food = input("whats your favourite food: ")
fav_col = input("what is your faourite colour: ")
animal = input("what animal you will like: ")
fav_thi = input("whats gthe one thing you will love to do in your free time: ")
print("--"*50)
print("Doing some analysis")
time.sleep(5)
print(f"your name has {len(name)} words")
print(f"your city has {len(location)} words")
print(f"your age type is {type(age)}")
print("wait for some time for the results")
time.sleep(5)
print(f"Hi {name},here is your fun personality")
print(f"you are from {location},a place of dreams!")
print(f"you love eating {fav_food} and enjoy {fav_thi} in free time")
print(f"you lived approximatly {age*12} months")